//! `lock` owns reading `Cargo.lock` and enforces INV-LOCK-RESOLVED-TRUTH: the
//! gate audits the *resolved* graph, not the declared one, so a crate that
//! arrives only as somebody else's transitive dependency is still audited.
//!
//! The reader is line-oriented on purpose. Taking a TOML parser as a dependency
//! in order to police dependencies would be self-refuting, and the subset
//! `Cargo.lock` uses — `[[package]]` blocks of `key = "value"` pairs — needs no
//! general parser. Anything outside that subset is skipped rather than guessed
//! at, and a `[[package]]` block missing a name is reported, never silently
//! dropped.
//!
//! A package with no `source` key is local: a workspace member or a path
//! dependency. That is Cargo's own encoding of "this came from the filesystem,
//! not a registry", and it is what separates the crates the estate wrote from
//! the crates it took.

// ── The resolved package ────────────────────────────────────────────────────

/// One entry from the resolved dependency graph.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Resolved {
    /// Package name exactly as `Cargo.lock` spells it.
    pub name: String,
    /// Resolved version.
    pub version: String,
    /// True when the package has no `source` key, meaning Cargo resolved it
    /// from the filesystem — a workspace member or a path dependency.
    pub local: bool,
}

/// A `[[package]]` block that could not be read.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LockError {
    /// A package block declared no `name`.
    NamelessPackage {
        /// Line where the offending block opened.
        line: usize,
    },
}

impl std::fmt::Display for LockError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NamelessPackage { line } => {
                write!(f, "[[package]] block at line {line} has no name")
            }
        }
    }
}

impl std::error::Error for LockError {}

// ── Reading ─────────────────────────────────────────────────────────────────

#[derive(Default)]
struct Pending {
    opened_at: usize,
    name: Option<String>,
    version: Option<String>,
    has_source: bool,
    open: bool,
}

/// Reads every `[[package]]` block out of a `Cargo.lock`.
pub fn parse(text: &str) -> Result<Vec<Resolved>, LockError> {
    let mut out = Vec::new();
    let mut pending = Pending::default();

    for (index, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.starts_with('[') {
            flush(&mut pending, &mut out)?;
            pending = Pending { opened_at: index + 1, open: line == "[[package]]", ..Pending::default() };
            continue;
        }
        if !pending.open {
            continue;
        }
        match key_and_value(line) {
            Some(("name", value)) => pending.name = Some(value.to_string()),
            Some(("version", value)) => pending.version = Some(value.to_string()),
            Some(("source", _)) => pending.has_source = true,
            _ => {}
        }
    }
    flush(&mut pending, &mut out)?;
    Ok(out)
}

fn flush(pending: &mut Pending, out: &mut Vec<Resolved>) -> Result<(), LockError> {
    if !pending.open {
        return Ok(());
    }
    let name = pending.name.take().ok_or(LockError::NamelessPackage { line: pending.opened_at })?;
    out.push(Resolved {
        name,
        version: pending.version.take().unwrap_or_default(),
        local: !pending.has_source,
    });
    pending.open = false;
    Ok(())
}

/// Splits `key = "value"` into its parts. Returns `None` for anything else,
/// including the quoted-key lines a v1 `[metadata]` table carries.
fn key_and_value(line: &str) -> Option<(&str, &str)> {
    let (key, value) = line.split_once('=')?;
    let key = key.trim();
    if key.is_empty() || !key.chars().all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-') {
        return None;
    }
    let value = value.trim();
    let unquoted = value.strip_prefix('"')?.strip_suffix('"')?;
    Some((key, unquoted))
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "lgwks_std"
version = "0.1.0"

[[package]]
name = "serde"
version = "1.0.219"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "5f1f0f0f"

[[package]]
name = "braid-ir"
version = "0.1.0"
"#;

    #[test]
    fn a_package_without_a_source_is_local() {
        let packages = parse(SAMPLE).unwrap();
        let local: Vec<&str> =
            packages.iter().filter(|p| p.local).map(|p| p.name.as_str()).collect();
        assert_eq!(local, vec!["lgwks_std", "braid-ir"]);
    }

    #[test]
    fn a_registry_package_carries_its_resolved_version() {
        let packages = parse(SAMPLE).unwrap();
        let serde = packages.iter().find(|p| p.name == "serde").expect("serde missing");
        assert_eq!(serde.version, "1.0.219");
        assert!(!serde.local);
    }

    #[test]
    fn the_top_level_version_key_is_not_read_as_a_package() {
        assert_eq!(parse(SAMPLE).unwrap().len(), 3);
    }

    #[test]
    fn a_v1_metadata_table_is_ignored() {
        let text = concat!(
            "[[package]]\nname = \"serde\"\nversion = \"1.0.0\"\nsource = \"registry+x\"\n\n",
            "[metadata]\n\"checksum serde 1.0.0 (registry+x)\" = \"abc\"\n"
        );
        let packages = parse(text).unwrap();
        assert_eq!(packages.len(), 1);
        assert_eq!(packages[0].name, "serde");
    }

    #[test]
    fn a_nameless_package_block_is_refused() {
        let text = "[[package]]\nversion = \"1.0.0\"\n";
        assert_eq!(parse(text), Err(LockError::NamelessPackage { line: 1 }));
    }

    #[test]
    fn an_empty_lock_resolves_to_nothing() {
        assert_eq!(parse("").unwrap(), Vec::new());
    }
}
